import type { Metadata } from "next";
import Link from "next/link";
import { CloudSun, Mail, Map, Phone } from "lucide-react";

import { FacebookIcon } from "@/components/ui/FacebookIcon";
import { PUBLIC_CONTACT } from "@/lib/site-links";

export const metadata: Metadata = {
  title: "Tra Linh — Ngoc Linh highlands",
  description: "Plan a responsible visit to Tra Linh: forests, Xe Dang culture, Ngoc Linh ginseng, journey guidance and official local contacts.",
  alternates: { canonical: "/en", languages: { "vi-VN": "/vi", "en-US": "/en", "x-default": "/" } },
  openGraph: { locale: "en_US", title: "Tra Linh — Ngoc Linh highlands", description: "Responsible travel information for Tra Linh in the Ngoc Linh highlands." },
};

const journeys = [
  { title: "Trekking beneath the old-growth canopy", duration: "Suggested duration: one day", difficulty: "Demanding — fitness and a local guide are required", season: "Best season is being verified locally", access: "Join only an approved programme or a group accompanied by a ranger or local guide.", steps: ["Confirm the route and weather", "Travel with the group beneath the forest canopy", "Leave before dark and carry all waste out"] },
  { title: "A Xe Dang village in the mist", duration: "Half day or an agreed overnight stay", difficulty: "Being verified with the local operator", season: "Being verified with the local operator", access: "Contact the village head or local representative before visiting.", steps: ["Ask for permission before arrival", "Learn about community spaces with a local host", "Ask before taking photographs and respect private areas"] },
  { title: "The medicinal-plant region", duration: "Visits follow the nursery schedule", difficulty: "Being verified with the local operator", season: "According to the conservation unit’s schedule", access: "Conservation areas accept only authorised scientific or organised groups.", steps: ["Confirm the opening schedule", "Follow the authorised guided route", "Do not touch or collect plants"] },
];

export default function EnglishHomePage() {
  return (
    <main id="noi-dung-chinh" className="min-h-screen bg-[#EEF1E9] text-[#10251A]">
      <section className="bg-[#10251A] px-5 pb-24 pt-36 text-[#EEF1E9] sm:px-8 lg:px-16">
        <div className="mx-auto max-w-[1180px]"><p className="text-xs font-semibold uppercase tracking-[0.25em] text-[#D5A84E]">Ngoc Linh highlands · Central Viet Nam</p><h1 className="mt-5 max-w-4xl font-serif text-5xl leading-[0.96] sm:text-7xl lg:text-8xl">Tra Linh</h1><p className="mt-7 max-w-2xl text-lg leading-8 text-[#D7E0D2]">A mountain community shaped by old-growth forest, Xe Dang culture and the conservation of Ngoc Linh ginseng. Plan slowly, confirm access locally and travel with respect.</p><div className="mt-9 flex flex-wrap gap-3"><Link href="#journeys" className="inline-flex min-h-12 items-center rounded-full bg-[#D5A84E] px-6 font-semibold text-[#10251A]">Plan a journey</Link><Link href="#contact" className="inline-flex min-h-12 items-center rounded-full border border-white/30 px-6 font-semibold">Contact locally</Link></div></div>
      </section>

      <section id="overview" className="px-5 py-20 sm:px-8 lg:px-16"><div className="mx-auto max-w-[1180px]"><p className="text-xs font-semibold uppercase tracking-[0.2em] text-[#5E7F3B]">Overview</p><h2 className="mt-4 max-w-3xl font-serif text-4xl sm:text-6xl">Forest, living culture and medicinal knowledge</h2><div className="mt-10 grid gap-5 md:grid-cols-3"><article className="rounded-3xl bg-white p-7"><h3 className="font-serif text-2xl">Old-growth forest</h3><p className="mt-3 leading-7 text-[#405347]">Cloud, steep terrain and humid forest define the landscape. Conditions can change quickly.</p></article><article className="rounded-3xl bg-white p-7"><h3 className="font-serif text-2xl">Xe Dang community</h3><p className="mt-3 leading-7 text-[#405347]">Visits should respect community routines, private spaces and consent for photography.</p></article><article className="rounded-3xl bg-white p-7"><h3 className="font-serif text-2xl">Ngoc Linh ginseng</h3><p className="mt-3 leading-7 text-[#405347]">Ginseng conservation areas have strict access rules. Never enter or collect plants without authorisation.</p></article></div></div></section>

      <section id="journeys" className="bg-[#EEE3CB] px-5 py-20 sm:px-8 lg:px-16"><div className="mx-auto max-w-[1180px]"><p className="text-xs font-semibold uppercase tracking-[0.2em] text-[#5E7F3B]">Verified planning notes</p><h2 className="mt-4 font-serif text-4xl sm:text-6xl">Three responsible journeys</h2><div className="mt-10 grid gap-6 lg:grid-cols-3">{journeys.map((journey) => <article key={journey.title} className="rounded-3xl bg-white p-7"><h3 className="font-serif text-2xl">{journey.title}</h3><dl className="mt-5 grid gap-3 text-sm"><div><dt className="font-semibold">Duration</dt><dd className="mt-1 text-[#405347]">{journey.duration}</dd></div><div><dt className="font-semibold">Difficulty</dt><dd className="mt-1 text-[#405347]">{journey.difficulty}</dd></div><div><dt className="font-semibold">Season</dt><dd className="mt-1 text-[#405347]">{journey.season}</dd></div><div><dt className="font-semibold">Access</dt><dd className="mt-1 text-[#405347]">{journey.access}</dd></div></dl><ol className="mt-6 list-decimal space-y-2 pl-5 text-sm leading-6 text-[#405347]">{journey.steps.map((step) => <li key={step}>{step}</li>)}</ol></article>)}</div></div></section>

      <section id="travel-advice" className="px-5 py-20 sm:px-8 lg:px-16"><div className="mx-auto max-w-[1180px]"><h2 className="font-serif text-4xl sm:text-6xl">Before you travel</h2><div className="mt-10 grid gap-4 sm:grid-cols-2"><div className="rounded-3xl border border-[#10251A]/10 bg-white p-7"><CloudSun aria-hidden="true" className="size-7 text-[#5E7F3B]" /><h3 className="mt-4 font-serif text-2xl">Weather</h3><p className="mt-3 leading-7 text-[#405347]">Check the forecast, but confirm rain, fog and road conditions with a local contact before departure.</p></div><div className="rounded-3xl border border-[#10251A]/10 bg-white p-7"><Map aria-hidden="true" className="size-7 text-[#5E7F3B]" /><h3 className="mt-4 font-serif text-2xl">Access</h3><p className="mt-3 leading-7 text-[#405347]">Map points are a planning aid. Follow verified listings and do not treat approximate coordinates as entrances.</p></div></div></div></section>

      <section id="contact" className="bg-[#10251A] px-5 py-20 text-white sm:px-8 lg:px-16"><div className="mx-auto max-w-[1180px]"><p className="text-xs font-semibold uppercase tracking-[0.2em] text-[#D5A84E]">Official contact channels</p><h2 className="mt-4 font-serif text-4xl sm:text-6xl">Confirm your plan locally</h2><p className="mt-5 max-w-2xl leading-7 text-[#D7E0D2]">No booking form or payment is collected on this website. Contact the commune directly during office hours.</p><div className="mt-8 grid gap-3 sm:grid-cols-3"><a href={PUBLIC_CONTACT.facebookUrl} target="_blank" rel="noreferrer" className="inline-flex min-h-14 items-center gap-3 rounded-2xl border border-white/20 px-5 font-semibold"><FacebookIcon className="size-5" /> Facebook page</a><a href={`tel:${PUBLIC_CONTACT.phone}`} className="inline-flex min-h-14 items-center gap-3 rounded-2xl border border-white/20 px-5 font-semibold"><Phone aria-hidden="true" className="size-5" /> {PUBLIC_CONTACT.phoneLabel}</a><a href={`mailto:${PUBLIC_CONTACT.email}`} className="inline-flex min-h-14 min-w-0 items-center gap-3 rounded-2xl border border-white/20 px-5 text-sm font-semibold"><Mail aria-hidden="true" className="size-5 shrink-0" /><span className="break-all">{PUBLIC_CONTACT.email}</span></a></div></div></section>
    </main>
  );
}
